#!/usr/bin/env node

import {execSync, spawn} from "node:child_process";
import * as path from "node:path";

const prefix = path.join(execSync("npm root -g").toString().replace(/\n$/, ""),
    "reddit-scheduler");

const args = process.argv.slice(2);
spawn("npm", args.length
    ? [`--prefix=${prefix}`, "run", ...args]
    : [`--prefix=${prefix}`, "start"], {
  stdio: "inherit"
});
